global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "collector"
    static_configs:
      - targets: ["collector:2112"]

  - job_name: "aggregator"
    static_configs:
      - targets: ["aggregator:2112"]


